In [1]:
#import numpy as 'np'
import numpy as np

In [2]:
#create one dimensional numpy array using np.array()
a1=np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [3]:
#create two dimensional numpy array using np.array
a2=np.array([[11,12,13,14],[15,16,17,18]])
a2


array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [4]:
#attributes of 1d array
a1.shape,a1.ndim,a1.dtype,a1.size,type(a1)

((4,), 1, dtype('int32'), 4, numpy.ndarray)

In [5]:
#attributes of 2d array
a2.shape,a2.ndim,a2.dtype,a2.size,type(a2)

((2, 4), 2, dtype('int32'), 8, numpy.ndarray)

In [6]:
#array of shape (5,5) with only ones
a3=np.ones((5,5))
a3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
#array of shape (3,3,5) with only zeros
a4=np.zeros((3,3,5))
a4

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [8]:
#random array with numbers between 0,10 and size (7,2)
from numpy import random
a5=np.random.randint(10, size=(7,2))
a5

array([[9, 7],
       [7, 5],
       [6, 0],
       [6, 6],
       [9, 5],
       [7, 1],
       [5, 6]])

In [9]:
#random array of float between 0,1 of shape (3,5)
a6=np.random.random((3,5))
a6

array([[0.60977961, 0.28830959, 0.63656151, 0.84851715, 0.90511475],
       [0.03734398, 0.46974534, 0.98297032, 0.94234064, 0.5654853 ],
       [0.45488322, 0.16634158, 0.6690912 , 0.73422955, 0.98947704]])

In [10]:
#array of normally distributed random numbers
a7=np.random.normal((3,5))
a7

array([1.68130787, 4.75612507])

In [11]:
#set the random seed to 42
np.random.seed(42)

In [12]:
#random array of numbers between 0,10 of size(4,6)
a8=np.random.randint(10,size=(4,6))
a8

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [13]:
#copy the code from the cell above and run it again
a8=np.random.randint(10,size=(4,6))
a8

array([[8, 0, 9, 2, 6, 3],
       [8, 2, 4, 2, 6, 4],
       [8, 6, 1, 3, 8, 1],
       [9, 8, 9, 4, 1, 3]])

In [14]:
#the 0th index of the latest array
a8[0]

array([8, 0, 9, 2, 6, 3])

In [15]:
#first two rows of the latest array
a8[:2]

array([[8, 0, 9, 2, 6, 3],
       [8, 2, 4, 2, 6, 4]])

In [18]:
#first 2 values of the first 2 rows 
a8[:2,:2]

array([[8, 0],
       [8, 2]])

In [19]:
#random array of numbers between 0,10 and ones both of size (3,5)
a9=np.random.randint(10,size=(3,5)) 
a10=np.ones((3,5))
a9,a10

(array([[6, 7, 2, 0, 3],
        [1, 7, 3, 1, 5],
        [5, 9, 3, 5, 1]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [20]:
#add the two arrays together
a11=a9+a10
a11

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [21]:
#array of ones of shape(5,3)
a12=np.ones((5,3))
a12

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
#add the array of ones to the most recent array created(must get an error)
a11+a12

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [23]:
#do the same opertaion you just did but this time with transpose of one array
a12=np.transpose(a12)
a13=a11+a12
a13


array([[ 8.,  9.,  4.,  2.,  5.],
       [ 3.,  9.,  5.,  3.,  7.],
       [ 7., 11.,  5.,  7.,  3.]])

In [24]:

# Take the latest array to the power of 2 using the python way
a13**2

array([[ 64.,  81.,  16.,   4.,  25.],
       [  9.,  81.,  25.,   9.,  49.],
       [ 49., 121.,  25.,  49.,   9.]])

In [25]:
#do the same thing with numpy way
np.power(a13,2)

array([[ 64.,  81.,  16.,   4.,  25.],
       [  9.,  81.,  25.,   9.,  49.],
       [ 49., 121.,  25.,  49.,   9.]])

In [26]:
#Find the mean, min, max, standard deviation, variance of the latest array using np.mean()
a13.mean(),a13.min(),a13.max(),a13.std()

(5.866666666666666, 2.0, 11.0, 2.578543947441829)

In [27]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)
a14=np.random.randint(0,10,9).reshape(3,3)
a15=np.random.randint(0,10,6).reshape(3,2)
a14,a15

(array([[9, 1, 9],
        [3, 7, 6],
        [8, 7, 4]]),
 array([[1, 4],
        [7, 9],
        [8, 8]]))

In [28]:
# Perform a dot product on the two newest arrays you created
np.dot(a14,a15)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [29]:
# Create two arrays of random integers between 0 to 10 both of size (4, 3)
b=np.random.randint(10, size=(4,3))
b1=np.random.randint(10, size=(4,3))
b,b1

(array([[0, 8, 6],
        [8, 7, 0],
        [7, 7, 2],
        [0, 7, 2]]),
 array([[2, 0, 4],
        [9, 6, 9],
        [8, 6, 8],
        [7, 1, 0]]))

In [30]:
# Perform a hadamard product on the two newest arrays you created
b*b1

array([[ 0,  0, 24],
       [72, 42,  0],
       [56, 42, 16],
       [ 0,  7,  0]])

In [31]:
# Perform a dot product on the two newest arrays you created # Error anticipated
np.dot(b,b1)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [32]:

# Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both
np.dot(b.T,b1)

array([[128,  90, 128],
       [184,  91, 151],
       [ 42,  14,  40]])

In [33]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables
b2=np.random.randint(10,size=(3,1))
b3=np.random.randint(10,size=(3,1))
b2,b3

(array([[6],
        [6],
        [7]]),
 array([[4],
        [2],
        [7]]))

In [34]:
# Compare the two arrays with '>', '<=' and '=='
b2>b3,b2<=b3,b2==b3

(array([[ True],
        [ True],
        [False]]),
 array([[False],
        [False],
        [ True]]),
 array([[False],
        [False],
        [ True]]))

In [35]:
# Sort one of the arrays you just created in ascending order
np.sort(b)

array([[0, 6, 8],
       [0, 7, 8],
       [2, 7, 7],
       [0, 2, 7]])

In [36]:
# Sort the indexes of one of the arrays you just created
np.argsort(b)

array([[0, 2, 1],
       [2, 1, 0],
       [2, 0, 1],
       [0, 2, 1]], dtype=int64)

In [37]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(b)

1

In [38]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [39]:
# Find the indexes with the maximum values down the verticial axis of one of the arrays you created
np.argmax(b,axis=0)

array([1, 0, 0], dtype=int64)

In [40]:
# Find the indexes with the minimum values across the horizontal axis of one of the arrays you created
np.argmin(b,axis=0)

array([0, 1, 1], dtype=int64)

In [41]:
# Find the indexes with the minimum values across the horizontal axis of one of the arrays you created
np.argmin(b,axis=0)

array([0, 1, 1], dtype=int64)